name: Create Umami report
description: Produce an umamiReport and outputs from umami website last 24h period
branding:
  icon: bar-chart
  color: green
author: boly38
inputs:
  umami-cloud-api-key:
    description: (1) The umami CLOUD apiKey. If set, this masks input with "(2)" flag
    required: false
  umami-server:
    description: (2) The umami Hosted server instance.
    required: false
  umami-user:
    description: (2) The umami Hosted server instance user
    required: false
  umami-password:
    description: (2) The umami Hosted server instance password
    required: false
  umami-site-domain:
    description: The umami site domain name
    default: ''
    required: false
  umami-report-file:
    description: The umami report file to produce (skipped if empty)
    required: false
    default: ''
  umami-report-content:
    description: The umami report content to produce
    required: false
    default: 'pageviews|events|sessions|urls'
  umami-period:
    description: The umami report period
    required: false
    default: '24h'
  umami-unit:
    description: The umami report unit
    required: false
    default: 'hour'
  umami-tz:
    description: The umami report Timezone
    required: false
    default: 'Europe/Paris'
runs:
  using: 'node20'
  main: index.js