name: pnpm_patch
permissions:
  contents: write

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: SETUP - Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      # https://github.com/pnpm/action-setup
      - name: SETUP - Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: SETUP - Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: pnpm patch
        run: |
          git config --global user.email  'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git fetch --all
          git checkout main
          pnpm version patch
          git branch -f npmjs
          git push origin main npmjs --tags