name: TEST_PNPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: "${{ github.workspace }}"
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get orphan branch name
        id: get_branch
        run: echo "ORPHAN_BRANCH=$(jq -r .orphanBranch package.json)" >> $GITHUB_ENV

      # https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup vercel/ncc for packaging
        run: pnpm install -g @vercel/ncc

      - name: Setup deps
        run: pnpm install

      # skip node_modules in git using @vercel/ncc to package action
      - name: Package app - action autonomous package with deps in dist/
        run: ./.github/scripts/package.sh

      - name: DEPLOY package - on target orphan branch '${{ env.ORPHAN_BRANCH }}'
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.ORPHAN_BRANCH }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          force_orphan: true